# Generated by Django 2.0.5 on 2019-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authanalitics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aacharacter',
            name='isk_destroyed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aacharacter',
            name='isk_lost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aazkillmonth',
            name='isk_destroyed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aazkillmonth',
            name='isk_lost',
            field=models.BigIntegerField(default=0),
        ),
    ]
