# Generated by Django 2.2.2 on 2019-10-22 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authanalitics', '0002_auto_20190106_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='aacharacter',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 9, 29, 14, 783840)),
        ),
    ]
