# Generated by Django 2.2 on 2019-11-02 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authanalitics', '0004_auto_20191022_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aacharacter',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 9, 21, 29, 447221)),
        ),
        migrations.AlterField(
            model_name='aazkillmonth',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 9, 21, 29, 448124)),
        ),
    ]
