# Generated by Django 2.2 on 2019-11-12 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authanalitics', '0007_auto_20191111_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aacharacter',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 14, 22, 31, 948906)),
        ),
        migrations.AlterField(
            model_name='aazkillmonth',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 14, 22, 31, 949928)),
        ),
    ]
