# Generated by Django 2.2 on 2019-11-12 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authanalitics', '0008_auto_20191112_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aacharacter',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 14, 24, 11, 278893)),
        ),
        migrations.AlterField(
            model_name='aazkillmonth',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 14, 24, 11, 279823)),
        ),
    ]
