# Generated by Django 2.2.8 on 2020-01-06 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authanalitics', '0009_auto_20191112_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aacharacter',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 11, 0, 30, 173141)),
        ),
        migrations.AlterField(
            model_name='aazkillmonth',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 11, 0, 30, 174558)),
        ),
    ]
