# Generated by Django 2.2.8 on 2020-01-24 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authanalitics', '0010_auto_20200106_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='aacharacter',
            name='zk_12m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aacharacter',
            name='zk_3m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aacharacter',
            name='zk_6m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aacharacter',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 10, 49, 15, 109068)),
        ),
        migrations.AlterField(
            model_name='aazkillmonth',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 10, 49, 15, 110300)),
        ),
    ]
